/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RoomsLayoutImport } from './routes/rooms/layout'
import { Route as PeopleLayoutImport } from './routes/people/layout'
import { Route as ItemsLayoutImport } from './routes/items/layout'
import { Route as CompareLayoutImport } from './routes/compare/layout'
import { Route as IndexImport } from './routes/index'
import { Route as AboutIndexImport } from './routes/about/index'
import { Route as RoomsIdImport } from './routes/rooms/$id'
import { Route as PeopleIdImport } from './routes/people/$id'
import { Route as ItemsIdImport } from './routes/items/$id'

// Create/Update Routes

const RoomsLayoutRoute = RoomsLayoutImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRoute,
} as any)

const PeopleLayoutRoute = PeopleLayoutImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRoute,
} as any)

const ItemsLayoutRoute = ItemsLayoutImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRoute,
} as any)

const CompareLayoutRoute = CompareLayoutImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AboutIndexRoute = AboutIndexImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRoute,
} as any)

const RoomsIdRoute = RoomsIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RoomsLayoutRoute,
} as any)

const PeopleIdRoute = PeopleIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PeopleLayoutRoute,
} as any)

const ItemsIdRoute = ItemsIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ItemsLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareLayoutImport
      parentRoute: typeof rootRoute
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsLayoutImport
      parentRoute: typeof rootRoute
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleLayoutImport
      parentRoute: typeof rootRoute
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsLayoutImport
      parentRoute: typeof rootRoute
    }
    '/items/$id': {
      id: '/items/$id'
      path: '/$id'
      fullPath: '/items/$id'
      preLoaderRoute: typeof ItemsIdImport
      parentRoute: typeof ItemsLayoutImport
    }
    '/people/$id': {
      id: '/people/$id'
      path: '/$id'
      fullPath: '/people/$id'
      preLoaderRoute: typeof PeopleIdImport
      parentRoute: typeof PeopleLayoutImport
    }
    '/rooms/$id': {
      id: '/rooms/$id'
      path: '/$id'
      fullPath: '/rooms/$id'
      preLoaderRoute: typeof RoomsIdImport
      parentRoute: typeof RoomsLayoutImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface ItemsLayoutRouteChildren {
  ItemsIdRoute: typeof ItemsIdRoute
}

const ItemsLayoutRouteChildren: ItemsLayoutRouteChildren = {
  ItemsIdRoute: ItemsIdRoute,
}

const ItemsLayoutRouteWithChildren = ItemsLayoutRoute._addFileChildren(
  ItemsLayoutRouteChildren,
)

interface PeopleLayoutRouteChildren {
  PeopleIdRoute: typeof PeopleIdRoute
}

const PeopleLayoutRouteChildren: PeopleLayoutRouteChildren = {
  PeopleIdRoute: PeopleIdRoute,
}

const PeopleLayoutRouteWithChildren = PeopleLayoutRoute._addFileChildren(
  PeopleLayoutRouteChildren,
)

interface RoomsLayoutRouteChildren {
  RoomsIdRoute: typeof RoomsIdRoute
}

const RoomsLayoutRouteChildren: RoomsLayoutRouteChildren = {
  RoomsIdRoute: RoomsIdRoute,
}

const RoomsLayoutRouteWithChildren = RoomsLayoutRoute._addFileChildren(
  RoomsLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareLayoutRoute
  '/items': typeof ItemsLayoutRouteWithChildren
  '/people': typeof PeopleLayoutRouteWithChildren
  '/rooms': typeof RoomsLayoutRouteWithChildren
  '/items/$id': typeof ItemsIdRoute
  '/people/$id': typeof PeopleIdRoute
  '/rooms/$id': typeof RoomsIdRoute
  '/about': typeof AboutIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareLayoutRoute
  '/items': typeof ItemsLayoutRouteWithChildren
  '/people': typeof PeopleLayoutRouteWithChildren
  '/rooms': typeof RoomsLayoutRouteWithChildren
  '/items/$id': typeof ItemsIdRoute
  '/people/$id': typeof PeopleIdRoute
  '/rooms/$id': typeof RoomsIdRoute
  '/about': typeof AboutIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/compare': typeof CompareLayoutRoute
  '/items': typeof ItemsLayoutRouteWithChildren
  '/people': typeof PeopleLayoutRouteWithChildren
  '/rooms': typeof RoomsLayoutRouteWithChildren
  '/items/$id': typeof ItemsIdRoute
  '/people/$id': typeof PeopleIdRoute
  '/rooms/$id': typeof RoomsIdRoute
  '/about/': typeof AboutIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/items'
    | '/people'
    | '/rooms'
    | '/items/$id'
    | '/people/$id'
    | '/rooms/$id'
    | '/about'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/items'
    | '/people'
    | '/rooms'
    | '/items/$id'
    | '/people/$id'
    | '/rooms/$id'
    | '/about'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/items'
    | '/people'
    | '/rooms'
    | '/items/$id'
    | '/people/$id'
    | '/rooms/$id'
    | '/about/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareLayoutRoute: typeof CompareLayoutRoute
  ItemsLayoutRoute: typeof ItemsLayoutRouteWithChildren
  PeopleLayoutRoute: typeof PeopleLayoutRouteWithChildren
  RoomsLayoutRoute: typeof RoomsLayoutRouteWithChildren
  AboutIndexRoute: typeof AboutIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareLayoutRoute: CompareLayoutRoute,
  ItemsLayoutRoute: ItemsLayoutRouteWithChildren,
  PeopleLayoutRoute: PeopleLayoutRouteWithChildren,
  RoomsLayoutRoute: RoomsLayoutRouteWithChildren,
  AboutIndexRoute: AboutIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/compare",
        "/items",
        "/people",
        "/rooms",
        "/about/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/compare": {
      "filePath": "compare/layout.tsx"
    },
    "/items": {
      "filePath": "items/layout.tsx",
      "children": [
        "/items/$id"
      ]
    },
    "/people": {
      "filePath": "people/layout.tsx",
      "children": [
        "/people/$id"
      ]
    },
    "/rooms": {
      "filePath": "rooms/layout.tsx",
      "children": [
        "/rooms/$id"
      ]
    },
    "/items/$id": {
      "filePath": "items/$id.tsx",
      "parent": "/items"
    },
    "/people/$id": {
      "filePath": "people/$id.tsx",
      "parent": "/people"
    },
    "/rooms/$id": {
      "filePath": "rooms/$id.tsx",
      "parent": "/rooms"
    },
    "/about/": {
      "filePath": "about/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
